import { UserRole } from './roles.constant';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.SYSTEM_ADMIN]: [
    'municipalities:create',
    'municipalities:read',
    'municipalities:update',
    'users:create',
    'users:read',
    'users:update',
    'users:deactivate',
    'audit:read',
    'dashboard:read',
    'scian:read',
    'scian:update',
    'zones:read',
    'zones:create',
    'taxpayers:read',
    'determinations:read',
    'reports:read',
    'central-config:read',
    'central-config:manage',
  ],
  [UserRole.MUNICIPAL_ADMIN]: [
    'users:create',
    'users:read',
    'users:update',
    'users:deactivate',
    'audit:read',
    'dashboard:read',
    'scian:read',
    'zones:read',
    'zones:configure',
    'weights:read',
    'weights:create',
    'taxpayers:read',
    'taxpayers:create',
    'taxpayers:update',
    'taxpayers:bulk-upload',
    'determinations:read',
    'determinations:execute',
    'determinations:approve',
    'reports:read',
    'reports:export',
  ],
  [UserRole.TREASURY_OPERATOR]: [
    'dashboard:read',
    'scian:read',
    'zones:read',
    'weights:read',
    'taxpayers:read',
    'taxpayers:create',
    'taxpayers:update',
    'determinations:read',
    'reports:read',
  ],
  [UserRole.LEGAL_ANALYST]: [
    'dashboard:read',
    'audit:read',
    'scian:read',
    'determinations:read',
    'reports:read',
  ],
  [UserRole.COMPTROLLER_AUDITOR]: [
    'audit:read',
    'dashboard:read',
    'scian:read',
    'zones:read',
    'weights:read',
    'taxpayers:read',
    'determinations:read',
    'reports:read',
  ],
  [UserRole.VALIDADOR_TECNICO]: [
    'dashboard:read',
    'audit:read',
    'scian:read',
    'zones:read',
    'weights:read',
    'taxpayers:read',
    'determinations:read',
    'determinations:resolve_exception',
    'reports:read',
  ],
};
